### ISSUE TITLE
Giving apps Accessibility permissions in a script

### ISSUE THREAD

**Issue by jimratliff** [gerhard/setup#6]
One of your manual-setup items is: "allow SizeUp in Privacy > Accessibility"

Just an FYI: jacobsalmela/tccutil is a Python command-line tool (with the same name as Apple's built-in but very limited tool) to give specific applications permission to control the Mac using accessibility features. See [https://github.com/jacobsalmela/tccutil](url).

For example, for BetterTouchTool, I simply do:

`betterTouchTool_bundleID="com.hegenberg.BetterTouchTool"

sudo $run_tccutil_py --insert $betterTouchTool_bundleID --verbose

sudo $run_tccutil_py --enable $betterTouchTool_bundleID --verbose`

**Comment by gerhard** [comment]
Since the latest Mojave install in #9 I had to allow access to:

* Location Services for iStat Menus
* Contacts for Alfred
* Calendars for iStat Menus
* Accessibility for Alfred, iTerm, Logitech & SizeUp
* Full Disk Access to iTerm
* Automation for Alfred & SizeUp

The apps mostly take care of this, and they remind what needs to be enabled on startup, so I'm happy to just do that. The new checklist reflects this.
